/* JAYASONA PREDIKSI V3.2.3
   Individual prediction engine:
   - up to 10 most recent completed matches for each team (before kickoff)
   - home/away venue history when available
   - up to 10 exact H2H meetings (before kickoff)
   - league baseline only as fallback/shrinkage when historical evidence is missing
   - no fixed 44/27/29 or 50/50 prediction constants
*/
const VERSION = "3.2.3";
const state = {
  data: {matches:[]}, filter:"all", search:"",
  favorites:new Set(JSON.parse(localStorage.getItem("jayasona_favorites")||"[]")),
  logoCache:JSON.parse(localStorage.getItem("jayasona_logo_cache")||"{}"), predictionCache:new Map()
};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
const arrScore=v=>Array.isArray(v)?v.join(" - "):(v===null||v===undefined||v===""?"—":String(v));
const isCompleted=m=>String(m.status||"").toLowerCase()==="completed" || (Array.isArray(m.ft)&&m.ft.length>=2);
const isLive=m=>/running|live/i.test(String(m.status||""));
const teamKey=s=>String(s||"").trim().toLowerCase().replace(/\s+/g," ");
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function parseKickoff(v){const d=new Date(String(v||"")); return Number.isNaN(d.getTime())?0:d.getTime();}
function saveFav(){localStorage.setItem("jayasona_favorites",JSON.stringify([...state.favorites]));}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),1800);}
function normalizeMatches(){state.data.matches=(state.data.matches||[]).map(m=>({...m,ht:Array.isArray(m.ht)?m.ht:(m.ht_home!==undefined&&m.ht_away!==undefined?[Number(m.ht_home),Number(m.ht_away)]:null),ft:Array.isArray(m.ft)?m.ft:(m.final_home!==undefined&&m.final_away!==undefined?[Number(m.final_home),Number(m.final_away)]:null)}));}
function completedMatches(){return state.data.matches.filter(m=>isCompleted(m)&&Array.isArray(m.ft)&&m.ft.length>=2&&m.ft.every(Number.isFinite));}
function sortRecent(ms){return [...ms].sort((a,b)=>parseKickoff(a.kickoff)-parseKickoff(b.kickoff));}
function beforeKickoff(m,cutoff){const t=parseKickoff(cutoff);const k=parseKickoff(m.kickoff);return !t||!k||k<t;}
function teamHistory10(team,cutoff){const k=teamKey(team);return sortRecent(completedMatches().filter(m=>beforeKickoff(m,cutoff)&&(teamKey(m.home)===k||teamKey(m.away)===k))).slice(-10);}
function venueHistory10(team,venue,cutoff){const k=teamKey(team);return sortRecent(completedMatches().filter(m=>{if(!beforeKickoff(m,cutoff))return false;return venue==="home"?teamKey(m.home)===k:teamKey(m.away)===k;})).slice(-10);}
function h2hHistory10(homeTeam,awayTeam,cutoff){const h=teamKey(homeTeam),a=teamKey(awayTeam);return sortRecent(completedMatches().filter(m=>{if(!beforeKickoff(m,cutoff))return false;const mh=teamKey(m.home),ma=teamKey(m.away);return(mh===h&&ma===a)||(mh===a&&ma===h);})).slice(-10);}
function weightedMean(values){if(!values.length)return 0;let n=0,d=0;values.forEach((v,i)=>{const w=Math.pow(.82,values.length-1-i);n+=v*w;d+=w;});return d?n/d:0;}
function matchSampleStats(games,team){const k=teamKey(team);const rows=games.map(m=>{const home=teamKey(m.home)===k;const gf=Number(m.ft[home?0:1]||0),ga=Number(m.ft[home?1:0]||0);return{gf,ga,points:gf>ga?3:gf===ga?1:0,over:gf+ga>2.5?1:0};});const avg=(key,f)=>rows.length?weightedMean(rows.map(x=>x[key])):f;return{n:rows.length,gf:avg("gf",1.2),ga:avg("ga",1.2),points:avg("points",1),over:avg("over",.5),wins:rows.filter(x=>x.points===3).length,draws:rows.filter(x=>x.points===1).length,losses:rows.filter(x=>x.points===0).length};}
const leagueCache=new Map();
function leagueStats(league){const key=String(league||"");if(leagueCache.has(key))return leagueCache.get(key);const ms=completedMatches().filter(m=>String(m.league||"")===key);const hg=[],ag=[],tot=[];ms.forEach(m=>{const h=Number(m.ft[0]||0),a=Number(m.ft[1]||0);hg.push(h);ag.push(a);tot.push(h+a);});const avg=(a,f)=>a.length?weightedMean(a):f;const s={homeGoals:avg(hg,1.35),awayGoals:avg(ag,1.05),teamGoals:avg(hg.concat(ag),1.2),overRate:avg(tot.map(x=>x>2.5?1:0),.5),n:ms.length};leagueCache.set(key,s);return s;}
function teamStats(team,league,cutoff){const recent=teamHistory10(team,cutoff),home=venueHistory10(team,"home",cutoff),away=venueHistory10(team,"away",cutoff),base=leagueStats(league);const all=matchSampleStats(recent,team),hs=matchSampleStats(home,team),as=matchSampleStats(away,team);return{n:all.n,gf:all.gf,ga:all.ga,points:all.points,over:all.over,homeN:hs.n,awayN:as.n,homeGf:hs.n?hs.gf:base.homeGoals,homeGa:hs.n?hs.ga:base.awayGoals,awayGf:as.n?as.gf:base.awayGoals,awayGa:as.n?as.ga:base.homeGoals,last:recent.slice(-5).map(m=>{const h=teamKey(m.home)===teamKey(team),gf=Number(m.ft[h?0:1]||0),ga=Number(m.ft[h?1:0]||0);return gf>ga?"W":gf===ga?"D":"L";})};}
function poissonMass(k,lambda){let p=Math.exp(-lambda);for(let i=1;i<=k;i++)p*=lambda/i;return p;}
function normalize3(a,b,c){const s=a+b+c||1;let vals=[a/s,b/s,c/s].map(x=>Math.round(x*100));let diff=100-vals.reduce((x,y)=>x+y,0);const raw=[a/s,b/s,c/s];while(diff!==0){const idx=diff>0?raw.indexOf(Math.min(...raw)):vals.indexOf(Math.max(...vals));vals[idx]+=diff>0?1:-1;diff+=diff>0?-1:1;}return vals;}
function estimate(m){const cacheKey=String(m.id||"")+"|"+String(m.kickoff||"")+"|v323";if(state.predictionCache.has(cacheKey))return state.predictionCache.get(cacheKey);const cutoff=m.kickoff,league=leagueStats(m.league),H=teamStats(m.home,m.league,cutoff),A=teamStats(m.away,m.league,cutoff),h2h=h2hHistory10(m.home,m.away,cutoff),h2hH=matchSampleStats(h2h,m.home),h2hA=matchSampleStats(h2h,m.away);const leagueH=league.homeGoals||1.35,leagueA=league.awayGoals||1.05;
  let hAttack=H.n?H.gf:leagueH,hDefense=H.n?H.ga:leagueA,aAttack=A.n?A.gf:leagueA,aDefense=A.n?A.ga:leagueH;
  const hw=H.homeN?Math.min(.28,.08+H.homeN*.02):0,aw=A.awayN?Math.min(.28,.08+A.awayN*.02):0;
  hAttack=hAttack*(1-hw)+(H.homeN?H.homeGf:leagueH)*hw;hDefense=hDefense*(1-hw)+(H.homeN?H.homeGa:leagueA)*hw;
  aAttack=aAttack*(1-aw)+(A.awayN?A.awayGf:leagueA)*aw;aDefense=aDefense*(1-aw)+(A.awayN?A.awayGa:leagueH)*aw;
  // Shrink only the missing part toward the current league baseline.
  const shrink=(v,n,b)=>n>=10?v:(n?v*(n/10)+b*(1-n/10):b);
  hAttack=shrink(hAttack,H.n,leagueH);hDefense=shrink(hDefense,H.n,leagueA);aAttack=shrink(aAttack,A.n,leagueA);aDefense=shrink(aDefense,A.n,leagueH);
  let lambdaH=.58*hAttack+.42*aDefense,lambdaA=.58*aAttack+.42*hDefense;
  // Form correction from the same last-10 samples.
  lambdaH*=clamp(1+(H.points-1)*.065+(H.gf-H.ga)*.022,.84,1.18);lambdaA*=clamp(1+(A.points-1)*.065+(A.gf-A.ga)*.022,.84,1.18);
  // Exact-pair H2H is capped so it informs the model without overpowering current form.
  if(h2h.length){const w=Math.min(.24,.05+h2h.length*.019);lambdaH=(1-w)*lambdaH+w*Math.max(.25,h2hH.gf);lambdaA=(1-w)*lambdaA+w*Math.max(.20,h2hA.gf);const edge=clamp((h2hH.points-h2hA.points)*.032,-.09,.09);lambdaH*=1+edge;lambdaA*=1-edge;}
  lambdaH=clamp(lambdaH,.20,4.2);lambdaA=clamp(lambdaA,.20,4.2);
  let home=0,draw=0,away=0,over=0,best={p:-1,h:0,a:0};for(let h=0;h<=10;h++)for(let a=0;a<=10;a++){const p=poissonMass(h,lambdaH)*poissonMass(a,lambdaA);if(h>a)home+=p;else if(h===a)draw+=p;else away+=p;if(h+a>=3)over+=p;if(p>best.p)best={p,h,a};}const [hp,dp,ap]=normalize3(home,draw,away);const overPct=Math.round(clamp(over*100,5,95));const htH=lambdaH*.44,htA=lambdaA*.44;let bestHT={p:-1,h:0,a:0};for(let h=0;h<=6;h++)for(let a=0;a<=6;a++){const p=poissonMass(h,htH)*poissonMass(a,htA);if(p>bestHT.p)bestHT={p,h,a};}
  const evidence=Math.min(H.n,10)+Math.min(A.n,10)+Math.min(h2h.length,10),coverage=(Math.min(H.n,10)+Math.min(A.n,10)+Math.min(h2h.length,10))/30;const confidence=Math.round(clamp(35+coverage*48+(H.homeN?3:0)+(A.awayN?3:0),35,94));const result={home:hp,draw:dp,away:ap,over:overPct,under:100-overPct,score:`${best.h}-${best.a}`,htft:`${bestHT.h}-${bestHT.a} / ${best.h}-${best.a}`,lambdaH,lambdaA,samplesH:H.n,samplesA:A.n,h2hSamples:h2h.length,formH:H.last.join(""),formA:A.last.join(""),confidence,hasIndividualHistory:H.n>0||A.n>0||h2h.length>0,coverage:Math.round(coverage*100)};state.predictionCache.set(cacheKey,result);return result;}
function initials(name){return String(name||"").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"?";}function teamLogoUrl(team){return state.logoCache[String(team||"").trim()]||"";}
const LOGO_ALIASES={"red bull salzburg":"FC Red Bull Salzburg","rapid wien":"SK Rapid","west bromwich albion":"West Bromwich Albion F.C.","charlton athletic":"Charlton Athletic F.C.","queens park rangers":"Queens Park Rangers F.C.","cardiff city":"Cardiff City F.C.","millwall":"Millwall F.C.","wrexham":"Wrexham A.F.C.","barnsley":"Barnsley F.C.","blackpool":"Blackpool F.C.","manchester city":"Manchester City F.C.","lazio":"S.S. Lazio","liverpool":"Liverpool F.C.","everton":"Everton F.C."};
async function fetchLogo(team){const key=String(team||"").trim();if(!key)return"";if(state.logoCache[key])return state.logoCache[key];const q=LOGO_ALIASES[teamKey(key)]||key;const urls=[`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(q)}`,`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q+" football club crest")}&gsrnamespace=6&gsrlimit=5&prop=imageinfo&iiprop=url&format=json&origin=*`];for(const url of urls){try{const r=await fetch(url,{cache:"no-store",mode:"cors"});if(!r.ok)continue;const j=await r.json();let src=j.thumbnail?.source||j.originalimage?.source||"";if(!src&&j.query?.pages)for(const p of Object.values(j.query.pages))src=src||p.imageinfo?.[0]?.url||p.thumbnail?.source||"";if(src){state.logoCache[key]=src;localStorage.setItem("jayasona_logo_cache",JSON.stringify(state.logoCache));return src;}}catch(e){}}return"";}
function logoHtml(team){const src=teamLogoUrl(team);return`<div class="logo">${src?`<img src="${esc(src)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:`<span class="logo-fallback">${esc(initials(team))}</span>`}</div>`;}
function statusInfo(m){if(isLive(m))return{text:"● LIVE",cls:"live"};return{text:"MENDATANG",cls:"upcoming"};}function timeOnly(k){const s=String(k||""),x=s.match(/(\d{1,2}:\d{2}\s*(?:AM|PM))/i);return x?x[1].toUpperCase():s;}
function matchesForDisplay(){const q=state.search.toLowerCase().trim();return state.data.matches.filter(m=>{const hay=`${m.home||""} ${m.away||""} ${m.league||""}`.toLowerCase();if(q&&!hay.includes(q))return false;if(isCompleted(m))return false;if(state.filter==="live"&&!isLive(m))return false;if(state.filter==="upcoming"&&isLive(m))return false;if(state.filter==="favorite"&&!state.favorites.has(m.id))return false;return true;});}
function renderQuick(){const all=[];for(const m of matchesForDisplay()){for(const t of[m.home,m.away])if(t&&!all.includes(t))all.push(t);if(all.length>=10)break;}$('quickClubs').innerHTML=all.slice(0,8).map(t=>`<button class="quick" data-club="${esc(t)}">⚽ ${esc(t)}</button>`).join("");document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>{$('search').value=b.dataset.club;state.search=b.dataset.club;render();});}
function card(m){const s=statusInfo(m),p=estimate(m),fav=state.favorites.has(m.id),ht=Array.isArray(m.ht)?arrScore(m.ht):p.htft.split(" / ")[0],historyLabel=p.hasIndividualHistory?`HISTORI ${p.samplesH}/10 · ${p.samplesA}/10 · H2H ${p.h2hSamples}/10`:`BASELINE · HISTORI BELUM TERSEDIA`;return`<article class="match-card"><div class="card-top"><span>${esc(timeOnly(m.kickoff))}</span><span class="status ${s.cls}">${s.text}</span></div><div class="teams"><div class="team">${logoHtml(m.home)}<div class="team-name">${esc(m.home)}</div></div><div class="scorebox"><div class="score">— - —</div><div class="period">${isLive(m)?"LIVE":"MENDATANG"}</div></div><div class="team">${logoHtml(m.away)}<div class="team-name">${esc(m.away)}</div></div></div><div class="metrics"><div class="metric"><span class="label">HOME</span><span class="value">${p.home}%</span></div><div class="metric"><span class="label">DRAW</span><span class="value">${p.draw}%</span></div><div class="metric"><span class="label">AWAY</span><span class="value">${p.away}%</span></div><div class="metric"><span class="label">OVER 2.5</span><span class="value">${p.over}%</span></div><div class="metric"><span class="label">UNDER 2.5</span><span class="value">${p.under}%</span></div><div class="metric"><span class="label">SKOR MODEL</span><span class="value">${esc(p.score)}</span></div></div><div class="evidence">${esc(historyLabel)} · CONFIDENCE ${p.confidence}%</div><div class="actions"><button class="action favorite ${fav?'active':''}" data-fav="${esc(m.id)}">${fav?'★ Favorit':'☆ Favorit'}</button><button class="action detail" data-detail="${esc(m.id)}">Detail pertandingan</button></div></article>`;}
function render(){const ms=matchesForDisplay(),groups={};for(const m of ms)(groups[m.league||"SABA CLUB FRIENDLY · PES 21"]||=[]).push(m);let html="";for(const[league,arr]of Object.entries(groups)){html+=`<div class="league-head"><span>⚽ ${esc(league)}</span><span class="league-count">${arr.length} pertandingan</span></div>`;html+=arr.map(card).join("");}$('matchList').innerHTML=html;$('empty').classList.toggle('hidden',!!ms.length);bindCards();}
function bindCards(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const id=b.dataset.fav;if(state.favorites.has(id))state.favorites.delete(id);else state.favorites.add(id);saveFav();render();toast(state.favorites.has(id)?'Ditambahkan ke Favorit':'Dihapus dari Favorit');});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const m=state.data.matches.find(x=>String(x.id)===String(b.dataset.detail));if(!m)return;const p=estimate(m);alert(`${m.home} vs ${m.away}\n\nLiga: ${m.league||'-'}\nKickoff: ${m.kickoff||'-'}\nStatus: ${m.status||'-'}\n\nPREDIKSI V3.2.3 — INDIVIDUAL\nHome ${p.home}% · Draw ${p.draw}% · Away ${p.away}%\nOver 2.5 ${p.over}% · Under 2.5 ${p.under}%\nSkor model: ${p.score}\nHT/FT: ${p.htft}\n\n10 LAGA ${m.home}: ${p.samplesH}/10\n10 LAGA ${m.away}: ${p.samplesA}/10\nH2H: ${p.h2hSamples}/10\nConfidence: ${p.confidence}%\n\n${p.hasIndividualHistory?'Model menggunakan histori yang tersedia sebelum kickoff.':'Histori tim/H2H belum tersedia; baseline liga digunakan sebagai fallback, bukan prediksi individual.'}`);});}
async function load(){try{const r=await fetch('data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);state.data=await r.json();normalizeMatches();leagueCache.clear();state.predictionCache.clear();renderQuick();render();const teams=[...new Set(matchesForDisplay().flatMap(m=>[m.home,m.away]).filter(Boolean))];const results=await Promise.all(teams.slice(0,24).map(t=>fetchLogo(t)));if(results.some(Boolean))render();}catch(e){console.error(e);$('matchList').innerHTML='<div class="empty">Gagal memuat data.json. Pastikan file data.json tetap ada di repository.</div>';}}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render();});$('search').addEventListener('input',e=>{state.search=e.target.value;render();});$('searchToggle').onclick=()=>{$('searchWrap').scrollIntoView({behavior:'smooth',block:'center'});$('search').focus();};$('menuToggle').onclick=()=>toast('JAYASONA PREDIKSI V'+VERSION);document.querySelectorAll('.bottom-item').forEach(b=>b.onclick=()=>{const v=b.dataset.bottom;if(v==='favorite'){state.filter='favorite';}else if(v==='live'){state.filter='live';}else if(v==='home'){state.filter='all';}else{toast('Menu JAYASONA PREDIKSI V'+VERSION);return;}document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));document.querySelectorAll('.bottom-item').forEach(x=>x.classList.toggle('active',x===b));render();});load();
